aws_region         = "us-east-1"
key_name           = "your-ssh-key-name"
tmdb_api_key       = "your-tmdb-api-key"
dockerhub_username = "your-dockerhub-username"
dockerhub_password = "your-dockerhub-password"
